server:
  port: ${server_port:8083}
spring:
  datasource:
    url: jdbc:mysql://120.24.22.221:8082/user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: cn.mailke.user.entity
